# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin    : "air" # "default", "air", "contrast", "dark", "dirt", "mint", "sunrise"

# Site Settings
locale                   : "bg-BG"
title                    : "Програмиране на C"
title_separator          : "|"
name                     : &name "ТУЕС (ELSYS)"
description              : &description "Страница на курса по програмиране на C за 10 клас"
url                      : https://elsys.github.io
baseurl                  : "/c-programming"
repository               : "elsys/c-programming"
search                   : true
og_image                 : "/assets/images/logo.png"

author:
  name      : *name
  avatar    : "/assets/images/logo.png"
  bio       : "Страница на курса по програмиране на C за 10 клас"
  location  : "София, България"
  email     : "elsys-po@googlegroups.com"
  github    : "elsys"
  uri       : "http://www.elsys-bg.org/"
  foursquare: "v/туес-elsys/4c134b7f7f7f2d7f1fe1de68"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:year/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Bulgaria/Sofia


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  years:
    output: true
    permalink: about/:collection/:path/

compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
      related: true
  # _years
  - scope:
      path: ""
      type: years
    values:
      layout: single
      share: true

pinned_period: 604800
